name: SiegeBattle
main: Siege.SiegeBattleMain
version: Beta-1.2.1
api-version: 1.14
commands:
   sb:
      description: SiegeBattle basic commands.
      usage: /sb <something>
      permission: SiegeBattle.sb
      permission-message: Banana.
   start:
      description: SiegeBattle basic commands.
      usage: /start
      permission: SiegeBattle.sb
      permission-message: Banana.
   recall:
      description: SiegeBattle basic commands.
      usage: /recall
      aliases: r
      permission-message: Banana.
      default: true
   r:
      description: SiegeBattle basic commands.
      usage: /r
      aliases: r
      permission-message: Banana.
      default: true
   info:
      description: player info.
      usage: /info
      aliases: info
      permission-message: Banana.
      default: true